### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by hendisantika** [piomin/sample-spring-oauth2-microservices#3]
I already read your blog and how to test it,
But, when I am trying to login it was error.
I use your auth service security : user / password.

`http://localhost:8765/login?error`

Any suggest?

Thanks

**Comment by piomin** [comment]
Type root / password. 

I set these credentials in application.yml instead of defaults:
security:
  user:
    name: root
    password: password

**Comment by hendisantika** [comment]
Still cannot login with that credential

**Comment by hendisantika** [comment]
Still cannot login with that credential, @piomin.

security:
user:
name: root
password: password
