### ISSUE TITLE
如何把网关和资源服务绑定在一起，认证服务单独使用

### ISSUE THREAD

**Issue by ligson** [piomin/sample-spring-oauth2-microservices#8]
1.资源服务和认证服务分离
2. 网关中增加@EnableOAuth2Client

**Comment by ramazansakin** [comment]
Hi @ligson ,

Can you write with little more details in english, pls ?
Thnx

**Comment by ligson** [comment]
已经解决。

**Comment by ligson** [comment]
deploy  resourceserver     authserver  in different server
